### ISSUE TITLE
XA30: preparation of measurement system failed (missing CUDA driver XA30 Skyra)

### ISSUE THREAD

**Issue by Jolinda** [CMRR-C2P/MB#325]
XA30 on a Skyra. I first tried installing with a slightly older .zip file and ran into the error about not being able to find plink.exe and putty.reg. I tried just copying over the files into the customer seq and ice directories, but the sequences would not run with a "preparation of measurement system failed" error. I then tried running the installer again after editing the batch file to comment out the two "set tfil" lines that were causing the error (I know, I shouldn't have done this) and everything appeared to install correctly (although at no point has a script been able to reboot the mars -- I've been having to do that separately). Same "preparation failed" error when running the sequence.

Finally I did what I should have done earlier and got the new zip file. Rebooted the system, ran the installer, no errors (except script could not reboot the mars), rebooted the mars. "Preparation of measurement system failed", even if I choose "none" for reconstruction on the special tab. However, if I set emptyiceprogram=True in ideacmdtool then the sequence WILL run.

Did I fuck something up in my earlier attempt to install the sequence? Do you have any idea what's going on?

**Comment by Jolinda** [comment]
Update: I don't think it's my fault. I think it's related to the fact that the script can't reboot the MARS. If I "plink MARS", it asks for a login. I don't see any sort of authentication for the MARS in the installation script, so I assume the plink commands are all failing.

**Comment by Jolinda** [comment]
Update 2: It is fixed! I was wrong that the script was not rebooting the MARS, that was a red herring. But the problem was indeed the MARS, and the assumption in the script that XA30 systems will always have CUDA support, so no dummy driver was included in the installation package. Our puny old Skyra does not, in fact, have gpus. I copied the dummy driver from VE11E and all is well.

**Comment by eauerbach** [comment]
I thought I had fixed the dummy driver installation in the new installer for R017pre7, but it is still not working.

**Comment by HiroshiImai4** [comment]
Perhaps I am in the same situation. After the XA30A upgrade, I reinstalled R017pre7 on our Skyra and I get an error message "Preparation failed" and the scan will not start. This Skyra does not have a GPU. According to the info here, I understand that installing the dummy driver seems to solve my problem. What are the steps to do that?

**Comment by eauerbach** [comment]
Can you try with the latest - R017pre9?

**Comment by HiroshiImai4** [comment]
@eauerbach , Thanks for uploading the latest version. I will download and try it.

**Comment by Jolinda** [comment]
Okay it's working again. I needed to create the libcuda.so.1 link in /usr/lib, not /usr/lib32. I believe the batch script creates the links in lib32 if that directory exists (which it does) but that's not where they should be created on our system.

**Comment by HiroshiImai4** [comment]
I also installed pre9 and tested it yesterday, but the scan didn't start with the same error as before.  Similar to Jolinda's comment, the /usr/lib32 folder existed, but libcuda.so.1 existed in libcuda/usr/lib. I was able to get it to work with a few modifications to eja_checkNVIDIA.sh. The posts here helped me. Thanks.

**Comment by eauerbach** [comment]
Thanks for working this out...sorry it was broken.

Could you check if linking to /usr/lib/x86_64-linux-gnu works instead of /usr/lib? Ultimately I think that should be the correct preferred directory. I do not remember what I was thinking when I changed the default from /usr/lib to /usr/lib32—that really does not make any sense.

**Comment by eauerbach** [comment]
Or try this modified script (delete the manually created link in /usr/lib first):
https://www.dropbox.com/scl/fi/u3xrg7t5s9khh7doy7291/eja_checkNVIDIA.sh?rlkey=lqvpaf7erobkui52j1ie6j879&dl=0

**Comment by eauerbach** [comment]
Actually, forget about this; starting with R017pre10 I have isolated the GPU code so the CUDA driver will only be referenced if a GPU is actually present and enabled. So the script and dummy driver are no longer needed.

**Comment by NeuroimagingOL** [comment]
Dear all, I run into the same problem. We updated from VE11C to XA30 yesterday and the preparation of the sequence failed. I installed the latest version available on the webseite R017pre9 which I downloaded yesterday. Is there already a working version of pre10, which I can install or how can I get the sequence running? Any help would be appreciated, since almost all our studies are using the sequence.

Best regards,
Tina
